# Generated by Django 5.2.4 on 2025-07-10 09:22
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Enter a book genre (e.g. Science Fiction)',
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text="Enter the book's language (e.g. English, French)",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                (
                    'summary',
                    models.TextField(
                        help_text='Enter a brief description of the book',
                        max_length=1000,
                    ),
                ),
                ('imprint', models.CharField(max_length=200)),
                (
                    'ISBN',
                    models.CharField(
                        help_text='13 Character ISBN number',
                        max_length=13,
                        unique=True,
                        verbose_name='ISBN',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='catalog.author',
                    ),
                ),
                ('genre', models.ManyToManyField(to='catalog.genre')),
                (
                    'language',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='catalog.language',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                (
                    'uniqueId',
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text='Unique ID for this particular book across whole library',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('due_back', models.DateField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('m', 'Maintenance'),
                            ('o', 'On loan'),
                            ('a', 'Available'),
                            ('r', 'Reserved'),
                        ],
                        default='m',
                        help_text='Book availability',
                        max_length=1,
                    ),
                ),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to='catalog.book',
                    ),
                ),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
