# Generated by Django 5.2.4 on 2025-07-14 03:25
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imprint',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
