# Generated by Django 5.2.4 on 2025-07-23 04:10
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={
                'ordering': ['due_back'],
                'permissions': (
                    ('can_mark_returned', 'Set book as returned'),
                ),
            },
        ),
    ]
